version: '3.8'

networks:
  integration-test-example:

services:
  it_test:
    image: amazoncorretto:17.0.9-alpine3.18
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    networks:
      - integration-test-example
    command: ["./gradlew","clean","integrationTest"]
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lottery-assignment
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - integration-test-example